test2

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -7,9 +7,15 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v2
+       - uses: actions/checkout@v2
 
-      - name: Run a one-line script
+      - name: Greeting
+        run: echo "Hello, world!"
+
+      - name: Simulate an error
+        run: echo "About to fail" ; exit 1
+
+      - name: Another greeting
         run: echo "Hello, world!"
       # Runs a set of commands using the runners shell
       - name: Run a multi-line script
